export const popularStocks = [
    // Nifty 50 Components
    { symbol: "RELIANCE.NS", name: "Reliance Industries Ltd" },
    { symbol: "TCS.NS", name: "Tata Consultancy Services Ltd" },
    { symbol: "HDFCBANK.NS", name: "HDFC Bank Ltd" },
    { symbol: "ICICIBANK.NS", name: "ICICI Bank Ltd" },
    { symbol: "INFY.NS", name: "Infosys Ltd" },
    { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever Ltd" },
    { symbol: "ITC.NS", name: "ITC Ltd" },
    { symbol: "SBIN.NS", name: "State Bank of India" },
    { symbol: "BHARTIARTL.NS", name: "Bharti Airtel Ltd" },
    { symbol: "LT.NS", name: "Larsen & Toubro Ltd" },
    { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank Ltd" },
    { symbol: "AXISBANK.NS", name: "Axis Bank Ltd" },
    { symbol: "ASIANPAINT.NS", name: "Asian Paints Ltd" },
    { symbol: "HCLTECH.NS", name: "HCL Technologies Ltd" },
    { symbol: "MARUTI.NS", name: "Maruti Suzuki India Ltd" },
    { symbol: "TITAN.NS", name: "Titan Company Ltd" },
    { symbol: "BAJFINANCE.NS", name: "Bajaj Finance Ltd" },
    { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries Ltd" },
    { symbol: "NTPC.NS", name: "NTPC Ltd" },
    { symbol: "ONGC.NS", name: "Oil & Natural Gas Corporation Ltd" },
    { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement Ltd" },
    { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India Ltd" },
    { symbol: "NESTLEIND.NS", name: "Nestle India Ltd" },
    { symbol: "TATASTEEL.NS", name: "Tata Steel Ltd" },
    { symbol: "ADANIPORTS.NS", name: "Adani Ports and Special Economic Zone Ltd" },
    { symbol: "JSWSTEEL.NS", name: "JSW Steel Ltd" },
    { symbol: "INDUSINDBK.NS", name: "IndusInd Bank Ltd" },
    { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv Ltd" },
    { symbol: "GRASIM.NS", name: "Grasim Industries Ltd" },
    { symbol: "TATAMOTORS.NS", name: "Tata Motors Ltd" },
    { symbol: "CIPLA.NS", name: "Cipla Ltd" },
    { symbol: "WIPRO.NS", name: "Wipro Ltd" },
    { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance Company Ltd" },
    { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company Ltd" },
    { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories Ltd" },
    { symbol: "UPL.NS", name: "UPL Ltd" },
    { symbol: "TECHM.NS", name: "Tech Mahindra Ltd" },
    { symbol: "SHREECEM.NS", name: "Shree Cement Ltd" },
    { symbol: "DIVISLAB.NS", name: "Divi's Laboratories Ltd" },
    { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation Ltd" },
    { symbol: "IOC.NS", name: "Indian Oil Corporation Ltd" },
    { symbol: "COALINDIA.NS", name: "Coal India Ltd" },
    { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp Ltd" },
    { symbol: "EICHERMOT.NS", name: "Eicher Motors Ltd" },
    { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto Ltd" },
    { symbol: "HINDALCO.NS", name: "Hindalco Industries Ltd" },
    { symbol: "VEDL.NS", name: "Vedanta Ltd" },
  
    // Next 50 (Nifty Next 50)
    { symbol: "ADANIENT.NS", name: "Adani Enterprises Ltd" },
    { symbol: "ADANIGREEN.NS", name: "Adani Green Energy Ltd" },
    { symbol: "ADANITRANS.NS", name: "Adani Transmission Ltd" },
    { symbol: "AMBUJACEM.NS", name: "Ambuja Cements Ltd" },
    { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals Enterprise Ltd" },
    { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma Ltd" },
    { symbol: "DMART.NS", name: "Avenue Supermarts Ltd (D-Mart)" },
    { symbol: "BANDHANBNK.NS", name: "Bandhan Bank Ltd" },
    { symbol: "BERGEPAINT.NS", name: "Berger Paints India Ltd" },
    { symbol: "BIOCON.NS", name: "Biocon Ltd" },
    { symbol: "BOSCHLTD.NS", name: "Bosch Ltd" },
    { symbol: "BRITANNIA.NS", name: "Britannia Industries Ltd" },
    { symbol: "COLPAL.NS", name: "Colgate-Palmolive (India) Ltd" },
    { symbol: "DLF.NS", name: "DLF Ltd" },
    { symbol: "GAIL.NS", name: "GAIL (India) Ltd" },
    { symbol: "GODREJCP.NS", name: "Godrej Consumer Products Ltd" },
    { symbol: "HDFCAMC.NS", name: "HDFC Asset Management Company Ltd" },
    { symbol: "HAVELLS.NS", name: "Havells India Ltd" },
    { symbol: "HINDPETRO.NS", name: "Hindustan Petroleum Corporation Ltd" },
    { symbol: "IDEA.NS", name: "Vodafone Idea Ltd" },
    { symbol: "IGL.NS", name: "Indraprastha Gas Ltd" },
    { symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power Ltd" },
    { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance Ltd" },
    { symbol: "LUPIN.NS", name: "Lupin Ltd" },
    { symbol: "M&M.NS", name: "Mahindra & Mahindra Ltd" },
    { symbol: "MARICO.NS", name: "Marico Ltd" },
    { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance Ltd" },
    { symbol: "NAUKRI.NS", name: "Info Edge (India) Ltd" },
    { symbol: "PIDILITIND.NS", name: "Pidilite Industries Ltd" },
    { symbol: "PNB.NS", name: "Punjab National Bank" },
    { symbol: "RECLTD.NS", name: "REC Ltd" },
    { symbol: "SIEMENS.NS", name: "Siemens Ltd" },
    { symbol: "SRF.NS", name: "SRF Ltd" },
    { symbol: "SAIL.NS", name: "Steel Authority of India Ltd" },
    { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals Ltd" },
    { symbol: "TORNTPOWER.NS", name: "Torrent Power Ltd" },
    { symbol: "TVSMOTOR.NS", name: "TVS Motor Company Ltd" },
    { symbol: "UBL.NS", name: "United Breweries Ltd" },
    { symbol: "MCDOWELL-N.NS", name: "United Spirits Ltd" },
    { symbol: "VOLTAS.NS", name: "Voltas Ltd" },
    { symbol: "ZEEL.NS", name: "Zee Entertainment Enterprises Ltd" },
  
    // Additional Popular Stocks
    { symbol: "PFC.NS", name: "Power Finance Corporation Ltd" },
    { symbol: "IRCTC.NS", name: "Indian Railway Catering & Tourism Corporation Ltd" },
    { symbol: "NAVINFLUOR.NS", name: "Navin Fluorine International Ltd" },
    { symbol: "AARTIIND.NS", name: "Aarti Industries Ltd" },
    { symbol: "ALKEM.NS", name: "Alkem Laboratories Ltd" },
    { symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital Ltd" },
    { symbol: "AUBANK.NS", name: "AU Small Finance Bank Ltd" },
    { symbol: "BHARATFORG.NS", name: "Bharat Forge Ltd" },
    { symbol: "CANBK.NS", name: "Canara Bank" },
    { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment and Finance Company Ltd" },
    { symbol: "ESCORTS.NS", name: "Escorts Kubota Ltd" },
    { symbol: "FEDERALBNK.NS", name: "Federal Bank Ltd" },
    { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals Ltd" },
    { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank Ltd" },
    { symbol: "MANAPPURAM.NS", name: "Manappuram Finance Ltd" },
    { symbol: "NIACL.NS", name: "The New India Assurance Company Ltd" },
    { symbol: "PEL.NS", name: "Piramal Enterprises Ltd" },
    { symbol: "RBLBANK.NS", name: "RBL Bank Ltd" },
    { symbol: "SUNDARMFIN.NS", name: "Sundaram Finance Ltd" },
    { symbol: "TRENT.NS", name: "Trent Ltd" },
    { symbol: "WHIRLPOOL.NS", name: "Whirlpool of India Ltd" },
    { symbol: "AAPL", name: "Apple Inc" },
    { symbol: "MSFT", name: "Microsoft Corporation" },
    { symbol: "GOOGL", name: "Alphabet Inc (Google)" },
    { symbol: "AMZN", name: "Amazon.com Inc" },
    { symbol: "META", name: "Meta Platforms Inc (Facebook)" },
    { symbol: "TSLA", name: "Tesla Inc" },
    { symbol: "NVDA", name: "NVIDIA Corporation" },
    { symbol: "JPM", name: "JPMorgan Chase & Co" },
    { symbol: "V", name: "Visa Inc" },
    { symbol: "WMT", name: "Walmart Inc" },
    { symbol: "MA", name: "Mastercard Inc" },
    { symbol: "PG", name: "Procter & Gamble" },
    { symbol: "JNJ", name: "Johnson & Johnson" },
    { symbol: "UNH", name: "UnitedHealth Group" },
    { symbol: "HD", name: "Home Depot" },
    { symbol: "BAC", name: "Bank of America" },
    { symbol: "DIS", name: "Walt Disney Company" },
    { symbol: "PYPL", name: "PayPal Holdings" },
    { symbol: "ADBE", name: "Adobe Inc" },
    { symbol: "NFLX", name: "Netflix Inc" },
  
    // ============ EUROPE ============
    { symbol: "NESN.SW", name: "Nestlé (Switzerland)" },
    { symbol: "HSBA.L", name: "HSBC Holdings (UK)" },
    { symbol: "BP.L", name: "BP plc (UK)" },
    { symbol: "ULVR.L", name: "Unilever (UK)" },
    { symbol: "AZN.L", name: "AstraZeneca (UK)" },
    { symbol: "SAP.DE", name: "SAP SE (Germany)" },
    { symbol: "SAN.PA", name: "Sanofi (France)" },
    { symbol: "ASML.AS", name: "ASML Holding (Netherlands)" },
    { symbol: "LVMH.PA", name: "LVMH (France)" },
    { symbol: "SIEGn.DE", name: "Siemens AG (Germany)" },
  
    // ============ ASIA ============
    { symbol: "005930.KS", name: "Samsung Electronics (South Korea)" },
    { symbol: "9984.T", name: "SoftBank Group (Japan)" },
    { symbol: "BABA", name: "Alibaba Group (China)" },
    { symbol: "TSM", name: "Taiwan Semiconductor (TSMC)" },
    { symbol: "SONY", name: "Sony Group Corp (Japan)" },
    { symbol: "HMC", name: "Honda Motor Co (Japan)" },
    { symbol: "TM", name: "Toyota Motor (Japan)" },
    { symbol: "NTES", name: "NetEase Inc (China)" },
    { symbol: "PDD", name: "PDD Holdings (China)" },
    { symbol: "SBUX", name: "Starbucks Corp (Global)" },
  
    // ============ GLOBAL GIANTS ============
    { symbol: "RY.TO", name: "Royal Bank of Canada" },
    { symbol: "BHP.AX", name: "BHP Group (Australia)" },
    { symbol: "RIO.L", name: "Rio Tinto (UK/Australia)" },
    { symbol: "TCEHY", name: "Tencent Holdings (China)" },
    { symbol: "JD", name: "JD.com Inc (China)" },
    { symbol: "SNE", name: "Sony Corporation (Japan)" },
    { symbol: "PTR", name: "PetroChina (China)" },
    { symbol: "SHG", name: "Shinhan Financial Group (Korea)" },
    { symbol: "HYMTF", name: "Hyundai Motor (Korea)" },
    { symbol: "EBAY", name: "eBay Inc (Global)" }
  ];